# Generated by Django 3.2.9 on 2022-01-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_creator', models.TextField()),
                ('game_opponent', models.TextField()),
                ('game_over', models.BooleanField()),
                ('room_name', models.TextField()),
            ],
        ),
    ]
